src/Entity/Forum.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ForumRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Forum
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Author;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ForumAnswer", mappedBy="Forum", orphanRemoval=true)
     */
    private $forumAnswers;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Visible;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;


    public function __construct()
    {
        date_default_timezone_set('Europe/Paris');
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->Visible = 0;
        $this->forumAnswers = new ArrayCollection();
    }
    /**
     * @ORM\PreUpdate
     */
    public function updateUpdatedAt(): self
    {
        date_default_timezone_set('Europe/Paris');
        if (end($this->forumAnswers) == null)
            $this->updatedAt = $this->createdAt;
        else
            $this->updatedAt = end($this->forumAnswers)->getCreatedAt;
        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|ForumAnswer[]
     */
    public function getForumAnswers(): Collection
    {
        return $this->forumAnswers;
    }
    public function addForumAnswer(ForumAnswer $forumAnswer): self
    {
        if (!$this->forumAnswers->contains($forumAnswer)) {
            $this->forumAnswers[] = $forumAnswer;
            $forumAnswer->setForum($this);
        }

        return $this;
    }

    public function removeForumAnswer(ForumAnswer $forumAnswer): self
    {
        if ($this->forumAnswers->contains($forumAnswer)) {
            $this->forumAnswers->removeElement($forumAnswer);
            // set the owning side to null (unless already changed)
            if ($forumAnswer->getForum() === $this) {
                $forumAnswer->setForum(null);
            }
        }

        return $this;
    }
    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getVisible(): ?bool
    {
        return $this->Visible;
    }

    public function setVisible(bool $Visible): self
    {
        $this->Visible = $Visible;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
    public function __toString()
    {
        return $this->title;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Password;

    /** 
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="integer")
     */
    private $Groupe;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Booking", mappedBy="Participant")
     */
    private $Event;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ForumAnswer", mappedBy="Author",cascade={"remove"})
     */
    private $forumAnswers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    public function __construct()
    {
        $this->Groupe = 2;
        $this->Event = new ArrayCollection();
        $this->forumAnswers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }
    public function getUsername(): ?string
    {
        return $this->Email;
    }


    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getGroupe(): ?int
    {
        return $this->Groupe;
    }

    public function setGroupe(int $Groupe): self
    {
        $this->Groupe = $Groupe;

        return $this;
    }
    public function getRoles()
    {
        if ($this->Groupe == 1)
            return ['ROLE_ADMIN'];
        else if ($this->Groupe == 2)
            return ['ROLE_USER'];
    }
    public function getSalt()
    {
        return null;
    }
    public function eraseCredentials()
    {
    }
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->Email,
            $this->Password
        ]);
    }
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->Email,
            $this->Password
        ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|Booking[]
     */
    public function getEvent(): Collection
    {
        return $this->Event;
    }

    public function addEvent(Booking $event): self
    {
        if (!$this->Event->contains($event)) {
            $this->Event[] = $event;
            $event->addParticipant($this);
        }

        return $this;
    }

    public function removeEvent(Booking $event): self
    {
        if ($this->Event->contains($event)) {
            $this->Event->removeElement($event);
            $event->removeParticipant($this);
        }

        return $this;
    }
    public function __toString(): ?string
    {
        $firstnameAndName = $this->firstname . ' ' . $this->Name;
        return $firstnameAndName;
    }

    /**
     * @return Collection|ForumAnswer[]
     */
    public function getForumAnswers(): Collection
    {
        return $this->forumAnswers;
    }

    public function addForumAnswer(ForumAnswer $forumAnswer): self
    {
        if (!$this->forumAnswers->contains($forumAnswer)) {
            $this->forumAnswers[] = $forumAnswer;
            $forumAnswer->setAuthor($this);
        }

        return $this;
    }

    public function removeForumAnswer(ForumAnswer $forumAnswer): self
    {
        if ($this->forumAnswers->contains($forumAnswer)) {
            $this->forumAnswers->removeElement($forumAnswer);
            // set the owning side to null (unless already changed)
            if ($forumAnswer->getAuthor() === $this) {
                $forumAnswer->setAuthor(null);
            }
        }

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }
}

templates/pages/archers.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Les Archers
{% endblock %}
{% block body %}
	<div class="container text-center">
		<div class="row">
			{% for friend in ArcFriends %}
				<div class="col-md-4 mb-md-0 mb-4">
					<div class="card mt-4">
						<img class="card-img-top" src="{{ vich_uploader_asset(friend) }}" alt="Card image cap"/>
						<div class="card-body">
							<h5 class="card-title">
								{{ friend.name }}
							</h5>
							<p class="card-text">
								{{ friend.description|nl2br  }}
							</p>
							{% if friend.siteurl is not null %}
								<a href="{{ friend.siteurl }}" target="_blank" class="btn btn-primary">
									Leur site
								</a>
							{% endif %}
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/pages/classement.html.twig
{% extends 'base.html.twig' %}
{% block title 'Classement'%}
{% block body %}
	<div class="container mt-4 classement">
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Prénom</th>
					<th scope="col">Nom</th>
					<th scope="col">Score</th>
				</tr>
			</thead>
			<tbody>
				{% for people in rank %}
					<tr>
						<th scope="row">
							<span class="fa-stack fa-1x nb-rank">
								<i class="fas fa-trophy fa-stack-2x"></i>
								<strong class="fa-stack-1x calendar-text">{{ loop.index }}</strong>
							</span>
						</th>
						<td>{{people.Firstname}}</td>
						<td>{{people.Lastname}}</td>
						<td>{{people.Score}}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

	</div>
{% endblock  %}

templates/pages/documents.html.twig
{% extends 'base.html.twig' %}
{% block title %}
  Documents
{% endblock %}
{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="w-100">
        <h4>
          Réglement Général
        </h4>
      </div>
      <div>
        <a target="_blank" href="{{ asset('docs/general.pdf') }}">
          Le réglement général des tirs de l'UAANF
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title 'La Flêche Millamoise '%}
{% block stylesheets %}
	{{ encore_entry_link_tags('home') }}
{% endblock %}

{% block body %}
	<div class="contain">
		<div class="content">
			<h1 class="main-title">La flêche Millamoise</h1>

			<p class="home-content">
				L'association a été créé en XXXX.
				<br>
				Elle comporte X membres.
			</p>
			{% if lastPicture is not null %}
				<div class="LastPhoto mb-3">
					<h3 class="titre-lastAlbum mt-2">Les dernières actualités photos</h3>
					<div class="link">Photo ajoutée à l'album :
						<a href="{{ path('album.show',{id: lastAlbum.id , slug: lastAlbum.slug}) }}">{{ lastAlbum.title }}</a>
					</div>
					Ajoutée le
					{{ date }}
					<div class="lastAlbum-content mb-3 mt-3">
						<a href="#" data-featherlight="{{ vich_uploader_asset(lastPicture) }}">
							<img class="home-picture" src="{{ vich_uploader_asset(lastPicture) }}">
						</a>
					</div>
					<div class="mb-2 link">
						<a href="{{ path('list.albums') }}">Voir les toutes les photos</a>
					</div>
				</div>
			{% endif %}
			{% if NextEvent is not null %}
				<div class="LastPhoto p-3">
					<h3 class="titre-lastAlbum mt-2">Prochain événement à venir</h3>
					<h4 class="mb-3">{{NextEvent.title}}</h4>
					<div class="nextEventContent" id="toChange-js">
						<p class="text-justify">{{NextEvent.description|nl2br}}</p>
						<div class="link-home-calendar link">
							<a href="{{ path('public_booking_show', {'id': NextEvent.id}) }}">Voir l'événement</p>
						</a>
						<a href="{{path('public.calendar')}}">Voir le calendrier des événement</a>
					</div>
				</div>
			</div>

		{% endif %}
	</div>
	<aside>
		<div id="meteo">
			<h4 class="meteo-title">Météo à Millam</h4>
			<div class="spinner-border mt-5 mb-5" id="chargement-js" role="status">
				<span class="sr-only">Loading...</span>
			</div>
			<div class="meteo-load" id="js-meteo" style="display: none;">
				<div class="today" id="js-actualweather">
					<div id="icon-js" class="icon"></div>
					<div id="infos-js" class="infos"></div>
				</div>
				<div class="nextDays">
					<div id="js-weather1"></div>
					<div id="js-weather2"></div>
				</div>
			</div>
		</div>
		<div class="visit">
			<h5>Visiteurs:</h5>
			15500
		</div>
	</aside>
</div></div><!-- Footer --><footer class="page-footer font-small pt-4">
<div class="container-fluid text-center text-md-left footer-contain">
	<div class="row">
		<div class="col-md-3 mb-md-0 mb-3">
			<h5 class="text-uppercase contact_title">Où nous trouver ?</h5>
			<ul class="list-unstyled txt_contact">
				<li>
					XX XXXXXX XXXXXXXX
				</li>
				<li>
					XXXXX XXXXX
				</li>
				<li>
					XXXXXXXXXXXXXXX
				</li>
				<li>
					XXXXXXXXXXXXXXXX
				</li>
			</ul>
		</div>
		<div class="col-md-5 mb-md-0 mb-5">
			<iframe class="map" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10074.185252694377!2d2.2462488!3d50.8580851!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x34c73b61542638f6!2sLa%20fl%C3%A8che%20millamoise!5e0!3m2!1sfr!2sfr!4v1580247112081!5m2!1sfr!2sfr" width="auto" height="100%" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
		</div>
		<hr class="clearfix w-100 d-md-none pb-3">
		<div class="col-md-4 mb-md-0 mb-4 contact text-center">
			<h5 class="text-uppercase contact_title">Où nous contacter?</h5>
			<ul class="list-unstyled txt_contact">
				<li>
					<a href="tel:0606060606">
						<i class="fas fa-phone"></i>
						0606060606
					</a>
				</li>
				<li>
					<a href="https://www.facebook.com/La-fl%C3%A8che-Millamoise-2409764802583268/">
						<i class="fab fa-facebook-f"></i>
						La flèche Millamoise
					</a>
				</li>
				<li>
					<a href="mailto:exemple@exemple.fr">
						<i class="fas fa-envelope"></i>
						exemple@exemple.fr
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="footer-copyright text-center py-2">© 2020 Copyright:
	<a href="https://github.com/Tiiyto" target="_blank">
		Antonin Lavie</a>
</div></footer>{% endblock  %}{% block javascripts %}{{ encore_entry_script_tags('home') }}{% endblock %}