src/Entity/Ranking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RankingRepository")
 */
class Ranking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lastname;

    /**
     * @ORM\Column(type="float")
     */
    private $Score;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getScore(): ?float
    {
        return $this->Score;
    }

    public function setScore(float $Score): self
    {
        $this->Score = $Score;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		{% block stylesheets %}{% endblock %}
		<meta name="viewport" content="width=device-width,initial-scale=1.0">
		<link href="//cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.css" type="text/css" rel="stylesheet"/>
		<link href="//cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.gallery.min.css" type="text/css" rel="stylesheet"/>
		{{ encore_entry_link_tags('app') }}
		<link href="https://fonts.googleapis.com/css2?family=Allerta+Stencil&display=swap" rel="stylesheet">
		<link rel="icon" href="{{ asset('images/logo.png') }}"/>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="{{ path('home') }}">
				<img src="{{ asset('images/logo.png') }}" width="30" height="30" class="d-inline-block align-top">
				La flêche millamoise
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					{% if app.user %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle {% if current_menu is defined and current_menu == 'vieAsso' %}active {% endif %}" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Vie Associative
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" href="{{path('user.classement')}}">Classement</a>
								<a class="dropdown-item" href="{{ path('user.list.albums') }}">Photos</a>
								<a class="dropdown-item" href="{{ path('user.calendar') }}">Calendrier</a>
							</div>
						</li>
					{% endif %}
					<li class="nav-item">
						<a class="nav-link {% if current_menu is defined and current_menu == 'Events' %}active {% endif %}" href="{{path('public.calendar')}}">Evenements</a>

					</li>
					<li class="nav-item">
						<a class="nav-link {% if current_menu is defined and current_menu == 'albums' %}active {% endif %}" href="{{ path('list.albums') }}">Photos</a>
					</li>
					<li class="nav-item">
						<a class="nav-link {% if current_menu is defined and current_menu == 'forum' %}active {% endif %}" href="{{ path('forum') }}">Questions?</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle {% if current_menu is defined and current_menu == 'archers' %}active {% endif %}" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Liens utiles
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<a class="dropdown-item" href="{{ path('link.friends') }}">Amis</a>
							<a class="dropdown-item" href="{{ path('link.archer') }}">Archers</a>
							<a class="dropdown-item" href="{{ path('link.docs') }}">Documents</a>
						</div>
					</li>
				</ul>

				<ul class="nav navbar-nav ml-auto">
					<li class="nav-item stay">
						<a href="{{ path('login') }}" class="nav-link {% if current_menu is defined and current_menu == 'user' %}active {% endif %}" href="#">
							<i class="fas fa-user"></i>
							{% if app.user %}
								{{ app.user.firstname }}
							{% else %}
								Connexion
							{% endif %}
						</a>
					</li>
					{% if app.user %}
						<li class="nav-item">
							<a href="{{ path('logout') }}" class="nav-link">
								<i class="fas fa-sign-out-alt"></i>
								Se déconnecter
							</a>
						</li>
					{% endif %}
				</ul>
			</div>
		</nav>
		{% block body %}{% endblock %}
	</body>
</html></footer>{% block javascripts %}{% endblock %}<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script><script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script><script src="//cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.js" type="text/javascript" charset="utf-8"></script><script src="//cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.gallery.min.js" type="text/javascript" charset="utf-8"></script>{{ encore_entry_script_tags('app') }}</body></html></body></html>

templates/vich_uploader_image.html.twig
<a
	href="#" class="easyadmin-thumbnail" data-featherlight="#easyadmin-lightbox-{{ item.id }}" data-featherlight-close-on-click="anywhere">
	{# the second parameter is the name of the property with the UploadableField annotation #}
	<img src="{{ vich_uploader_asset(item, 'imageFile') }}">
</a>

<div
	id="easyadmin-lightbox-{{ item.id }}" class="easyadmin-lightbox">
	{# the second parameter is the name of the property with the UploadableField annotation #}
	<img src="{{ vich_uploader_asset(item, 'imageFile') }}">
</div>